# Generated by Django 3.1.1 on 2020-10-04 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gossip',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gossip',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gossip_picture'),
        ),
        migrations.CreateModel(
            name='Mesage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('content', models.TextField(max_length=600)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('unread', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
