# Generated by Django 3.1.1 on 2020-10-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_auto_20201004_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesage',
            old_name='unread',
            new_name='read',
        ),
    ]
