# Generated by Django 3.1.1 on 2020-10-10 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20201004_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
