# Generated by Django 3.1.1 on 2020-10-10 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialapp', '0007_auto_20201010_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gossip',
            name='good_one',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gossip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialapp.gossip')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
