# Generated by Django 3.1.1 on 2020-10-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Moscow', max_length=30),
        ),
    ]
