# Generated by Django 3.1.1 on 2020-10-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0013_auto_20201023_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='title',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
